server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.banking.notificationservice.dto,com.banking.accountservice.dto
  mail:
    host: maildev
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
